version: '3'
services:
    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
        ports:
            - "3306:3306"
    mailer:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
        environment:
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1
